name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar testes
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Testes simulados aprovados"
          exit 0

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload dos arquivos para deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # ou "dist", se você estiver usando React, Vite, etc.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy para o GitHub Pages
        uses: actions/deploy-pages@v2
